<?php
declare(strict_types=1);
// Statistiques Ligue 1 2026-27 verifiees par joueur (source fbref_players_l1_2026-27), relevees le 2026-09-09. Trois tables FBref squad agregees : Standard Stats, Shooting, Miscellaneous Stats. Uniquement les joueurs avec au moins un match joue.
// Fichier généré automatiquement, dernière mise à jour : 2026-09-09.
return array (
  'Hakimi' => 
  array (
    'mp' => 3,
    'starts' => 3,
    'minutes' => 270,
    'goals' => 0,
    'assists' => 0,
    'pk' => 0,
    'yellow' => 1,
    'red' => 0,
    'shots' => 7,
    'sot' => 1,
    'tackles' => 2,
    'interceptions' => 1,
  ),
  'Marquinhos' => 
  array (
    'mp' => 3,
    'starts' => 3,
    'minutes' => 270,
    'goals' => 2,
    'assists' => 0,
    'pk' => 0,
    'yellow' => 1,
    'red' => 0,
    'shots' => 2,
    'sot' => 2,
    'tackles' => 1,
    'interceptions' => 1,
  ),
  'Pacho' => 
  array (
    'mp' => 3,
    'starts' => 3,
    'minutes' => 270,
    'goals' => 0,
    'assists' => 0,
    'pk' => 0,
    'yellow' => 0,
    'red' => 0,
    'shots' => 0,
    'sot' => 0,
    'tackles' => 5,
    'interceptions' => 3,
  ),
  'Safonov' => 
  array (
    'mp' => 3,
    'starts' => 3,
    'minutes' => 270,
    'goals' => 0,
    'assists' => 0,
    'pk' => 0,
    'yellow' => 0,
    'red' => 0,
    'shots' => 0,
    'sot' => 0,
    'tackles' => 0,
    'interceptions' => 0,
  ),
  'Vitinha' => 
  array (
    'mp' => 3,
    'starts' => 3,
    'minutes' => 248,
    'goals' => 1,
    'assists' => 1,
    'pk' => 0,
    'yellow' => 0,
    'red' => 0,
    'shots' => 9,
    'sot' => 3,
    'tackles' => 2,
    'interceptions' => 4,
  ),
  'Zaïre-Emery' => 
  array (
    'mp' => 3,
    'starts' => 3,
    'minutes' => 212,
    'goals' => 0,
    'assists' => 0,
    'pk' => 0,
    'yellow' => 0,
    'red' => 0,
    'shots' => 4,
    'sot' => 1,
    'tackles' => 3,
    'interceptions' => 1,
  ),
  'Doué' => 
  array (
    'mp' => 3,
    'starts' => 3,
    'minutes' => 197,
    'goals' => 0,
    'assists' => 0,
    'pk' => 0,
    'yellow' => 0,
    'red' => 0,
    'shots' => 9,
    'sot' => 3,
    'tackles' => 7,
    'interceptions' => 2,
  ),
  'Ruiz' => 
  array (
    'mp' => 3,
    'starts' => 2,
    'minutes' => 177,
    'goals' => 0,
    'assists' => 2,
    'pk' => 0,
    'yellow' => 1,
    'red' => 0,
    'shots' => 2,
    'sot' => 2,
    'tackles' => 4,
    'interceptions' => 3,
  ),
  'Akliouche' => 
  array (
    'mp' => 3,
    'starts' => 2,
    'minutes' => 176,
    'goals' => 0,
    'assists' => 0,
    'pk' => 0,
    'yellow' => 0,
    'red' => 0,
    'shots' => 1,
    'sot' => 1,
    'tackles' => 3,
    'interceptions' => 4,
  ),
  'Kvaratskhelia' => 
  array (
    'mp' => 3,
    'starts' => 2,
    'minutes' => 157,
    'goals' => 0,
    'assists' => 1,
    'pk' => 0,
    'yellow' => 0,
    'red' => 0,
    'shots' => 6,
    'sot' => 2,
    'tackles' => 1,
    'interceptions' => 0,
  ),
  'Neves' => 
  array (
    'mp' => 2,
    'starts' => 2,
    'minutes' => 149,
    'goals' => 0,
    'assists' => 0,
    'pk' => 0,
    'yellow' => 0,
    'red' => 0,
    'shots' => 5,
    'sot' => 1,
    'tackles' => 2,
    'interceptions' => 4,
  ),
  'Torres' => 
  array (
    'mp' => 3,
    'starts' => 1,
    'minutes' => 144,
    'goals' => 2,
    'assists' => 0,
    'pk' => 0,
    'yellow' => 0,
    'red' => 0,
    'shots' => 5,
    'sot' => 2,
    'tackles' => 0,
    'interceptions' => 2,
  ),
  'Hernandez' => 
  array (
    'mp' => 2,
    'starts' => 1,
    'minutes' => 117,
    'goals' => 0,
    'assists' => 0,
    'pk' => 0,
    'yellow' => 1,
    'red' => 0,
    'shots' => 0,
    'sot' => 0,
    'tackles' => 0,
    'interceptions' => 1,
  ),
  'Beraldo' => 
  array (
    'mp' => 2,
    'starts' => 1,
    'minutes' => 84,
    'goals' => 0,
    'assists' => 0,
    'pk' => 0,
    'yellow' => 0,
    'red' => 0,
    'shots' => 0,
    'sot' => 0,
    'tackles' => 2,
    'interceptions' => 0,
  ),
  'Dembélé' => 
  array (
    'mp' => 2,
    'starts' => 1,
    'minutes' => 67,
    'goals' => 0,
    'assists' => 0,
    'pk' => 0,
    'yellow' => 0,
    'red' => 0,
    'shots' => 5,
    'sot' => 1,
    'tackles' => 0,
    'interceptions' => 0,
  ),
  'Godts' => 
  array (
    'mp' => 3,
    'starts' => 0,
    'minutes' => 96,
    'goals' => 0,
    'assists' => 1,
    'pk' => 0,
    'yellow' => 0,
    'red' => 0,
    'shots' => 4,
    'sot' => 0,
    'tackles' => 2,
    'interceptions' => 0,
  ),
  'Fernández' => 
  array (
    'mp' => 2,
    'starts' => 0,
    'minutes' => 28,
    'goals' => 0,
    'assists' => 0,
    'pk' => 0,
    'yellow' => 0,
    'red' => 0,
    'shots' => 0,
    'sot' => 0,
    'tackles' => 3,
    'interceptions' => 1,
  ),
  'Digne' => 
  array (
    'mp' => 1,
    'starts' => 0,
    'minutes' => 19,
    'goals' => 0,
    'assists' => 0,
    'pk' => 0,
    'yellow' => 0,
    'red' => 0,
    'shots' => 1,
    'sot' => 0,
    'tackles' => 0,
    'interceptions' => 0,
  ),
  'Mayulu' => 
  array (
    'mp' => 1,
    'starts' => 0,
    'minutes' => 19,
    'goals' => 0,
    'assists' => 0,
    'pk' => 0,
    'yellow' => 0,
    'red' => 0,
    'shots' => 0,
    'sot' => 0,
    'tackles' => 0,
    'interceptions' => 0,
  ),
);
